import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import ClientSidebar from "@/components/sidebar/client-sidebar";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider children={undefined}>
          <SidebarProvider>
            <ClientSidebar />
            <main className="bg-bgColor w-full text-[#fff]">
              <div className="flex flex-1 flex-col pt-5 gap-4 px-0 ">
                <div className=" min-h-screen flex-1 rounded-xl md:min-h-min">
                  {children}
                  <Toaster />
                </div>
              </div>
            </main>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
