import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ClientNavbar from "@/components/ClientNavbar";
import ClientFooter from "@/components/ClientFooter";

export const metadata: Metadata = {
  title: "DevStore",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>

      <body className="bg-black text-[#f5eeff]">
        <main>
          <AuthProvider children={undefined}>
            <ClientNavbar />

            <div className="max-w-[1440] mx-auto px-3 md:py-0">{children}</div>

            <ClientFooter />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
